name: Fix SelNexa printed CSS & add logo

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure assets directory
        run: mkdir -p "styles/scripts/assets"

      - name: Download logo JPG from live site
        run: |
          set -eux
          curl -fsSL -o "styles/scripts/assets/selnexa-logo.jpg" "https://www.selnexahealth.com/styles/scripts/assets/SelNexa%20Logo.jpg"
          ls -l styles/scripts/assets/selnexa-logo.jpg

      - name: Backup target HTML files
        run: |
          for f in "SelNexa Website/index.html" "index.html"; do
            if [ -f "$f" ]; then cp "$f" "$f.bak"; fi
          done

      - name: Clean printed CSS and update logo references (Python)
        run: |
          set -eux
          python3 - <<'PY'
          import re, sys, pathlib
          files = ["SelNexa Website/index.html", "index.html"]
          picture = '<picture class="site-logo"><source type="image/avif" srcset="styles/scripts/assets/selnexa-logo.avif"><source type="image/webp" srcset="styles/scripts/assets/selnexa-logo.webp"><img src="styles/scripts/assets/selnexa-logo.jpg" alt="SelNexa Health logo" class="logo-img" width="220" height="60" decoding="async" fetchpriority="high"></picture>'
          for fname in files:
              p = pathlib.Path(fname)
              if not p.is_file():
                  continue
              text = p.read_text(encoding="utf-8")
              # remove artifact marker
              text = text.replace("-->Skip to content", "")
              # remove long header { ... } blocks (non-greedy)
              text = re.sub(r"header\s*\{.*?\}", "", text, flags=re.S)
              # replace legacy logo filenames (percent-encoded and with spaces)
              text = re.sub(r"SelNexa%20Logo\.jpg", "styles/scripts/assets/selnexa-logo.jpg", text)
              text = re.sub(r"SelNexa Logo\.jpg", "styles/scripts/assets/selnexa-logo.jpg", text)
              # replace <img ... class="logo-img" ...> (class may be in any order)
              text = re.sub(r'(?is)<img\b[^>]*class=(["\'])[^\1]*?logo-img[^\1]*?\1[^>]*>', picture, text)
              p.write_text(text, encoding="utf-8")
          # update manifest.json if present
          m = pathlib.Path("manifest.json")
          if m.is_file():
              mt = m.read_text(encoding="utf-8")
              mt = re.sub(r"SelNexa%20Logo\.jpg", "styles/scripts/assets/selnexa-logo.jpg", mt)
              mt = re.sub(r"SelNexa Logo\.jpg", "styles/scripts/assets/selnexa-logo.jpg", mt)
              m.write_text(mt, encoding="utf-8")
          PY

      - name: Debug: git status / remotes / diff
        run: |
          git --no-pager status --porcelain
          git --no-pager diff --name-status || true
          echo "Git remote:"
          git remote -v || true
          echo "git config:"
          git config --list || true
          echo "Show any staged changes:"
          git --no-pager diff --staged --name-status || true
          echo "List of modified HTML files:"
          git ls-files -m || true

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git --no-pager diff --name-status --cached || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "CI: add selnexa-logo.jpg, remove printed CSS, update logo references"
            git push origin HEAD
          fi
