name: Fix SelNexa printed CSS & add logo

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure assets directory
        run: mkdir -p "styles/scripts/assets"

      - name: Download logo JPG from live site
        run: |
          set -eux
          curl -fsSL -o "styles/scripts/assets/selnexa-logo.jpg" "https://www.selnexahealth.com/styles/scripts/assets/SelNexa%20Logo.jpg" || { echo "curl failed"; ls -la styles/scripts/assets || true; exit 1; }
          ls -l styles/scripts/assets/selnexa-logo.jpg

      - name: Backup target HTML files
        run: |
          for f in "SelNexa Website/index.html" "index.html"; do
            if [ -f "$f" ]; then cp "$f" "$f.bak"; fi
          done

      - name: Clean printed CSS and update logo references (sed/awk)
        run: |
          set -eux
          picture='<picture class="site-logo"><source type="image/avif" srcset="styles/scripts/assets/selnexa-logo.avif"><source type="image/webp" srcset="styles/scripts/assets/selnexa-logo.webp"><img src="styles/scripts/assets/selnexa-logo.jpg" alt="SelNexa Health logo" class="logo-img" width="220" height="60" decoding="async" fetchpriority="high"></picture>'
          for f in "SelNexa Website/index.html" "index.html"; do
            [ -f "$f" ] || continue
            cp "$f" "$f.bak"
            # remove the large printed CSS block starting at 'header {' until the marker '-->Skip to content'
            sed '/header\s*{/,/-->Skip to content/ d' "$f" > "$f.tmp1"
            # normalize legacy filenames to the new asset path
            sed -E 's/SelNexa%20Logo\.jpg/styles\/scripts\/assets\/selnexa-logo.jpg/g; s/SelNexa Logo\.jpg/styles\/scripts\/assets\/selnexa-logo.jpg/g' "$f.tmp1" > "$f.tmp2"
            # replace any line that contains the logo fallback img (class="logo-img") with the picture markup
            awk -v pic="$picture" '{ if ($0 ~ /class="logo-img"/) { print pic } else print $0 }' "$f.tmp2" > "$f.clean"
            mv "$f.clean" "$f"
            rm -f "$f.tmp1" "$f.tmp2"
          done
          # update manifest.json if present
          if [ -f manifest.json ]; then
            sed -E 's/SelNexa%20Logo\.jpg/styles\/scripts\/assets\/selnexa-logo.jpg/g; s/SelNexa Logo\.jpg/styles\/scripts\/assets\/selnexa-logo.jpg/g' manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json
          fi

      - name: Debug: git status / remotes / diff
        run: |
          git --no-pager status --porcelain
          git --no-pager diff --name-status || true
          echo "Git remote:"
          git remote -v || true
          echo "git config:"
          git config --list || true
          echo "Show any staged changes:"
          git --no-pager diff --staged --name-status || true
          echo "List of modified HTML files:"
          git ls-files -m || true

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git --no-pager diff --name-status --cached || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "CI: add selnexa-logo.jpg, remove printed CSS, update logo references"
            git push origin HEAD
          fi
