name: "Run all: generate assets, form test, lighthouse"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Generate image variants
        id: gen
        run: |
          mkdir -p styles/scripts/assets
          if [ -f "styles/scripts/assets/SelNexa Health Logo Full.jpg" ]; then
            magick "styles/scripts/assets/SelNexa Health Logo Full.jpg" -resize 180 "styles/scripts/assets/selnexa-logo.webp"
            magick "styles/scripts/assets/SelNexa Health Logo Full.jpg" -resize 360 "styles/scripts/assets/selnexa-logo@2x.webp"
            magick "styles/scripts/assets/SelNexa Health Logo Full.jpg" -resize 180 "styles/scripts/assets/selnexa-logo.avif"
            magick "styles/scripts/assets/SelNexa Health Logo Full.jpg" -resize 360 "styles/scripts/assets/selnexa-logo@2x.avif"
            magick "styles/scripts/assets/SelNexa Health Logo Full.jpg" -resize 180 -quality 85 "styles/scripts/assets/selnexa-logo.jpg"
            echo "generated=1" >> $GITHUB_OUTPUT
          else
            echo "generated=0" >> $GITHUB_OUTPUT
            echo "Source full JPG not found; skipping generation.";
          fi

      - name: Commit generated assets (if any)
        if: steps.gen.outputs.generated == '1'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add styles/scripts/assets/selnexa-logo.* || true
          git commit -m "CI: generate logo webp/avif variants" || echo "no new files"
          git push || echo "push failed"

      - name: FormSubmit test POST
        id: formtest
        run: |
          mkdir -p artifacts
          RESPONSE=$(curl -s -o /tmp/formresp.txt -w "%{http_code}" -X POST "https://formsubmit.co/keithtafangombe@gmail.com" -F "_subject=CI Test" -F "name=CI Test" -F "email=keithtafangombe+ci@test.example" -F "message=This is a test from GitHub Actions" ) || true
          echo "HTTP_CODE=$RESPONSE" > artifacts/response-meta.txt
          cp /tmp/formresp.txt artifacts/response-body.html || true

      - name: Run Lighthouse
        id: lighthouse
        run: |
          npm install -g lighthouse@10
          mkdir -p reports
          npx lighthouse https://www.selnexahealth.com --output=json --output=html --output-path=./reports/lighthouse-report || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: run-all-artifacts
          path: |
            artifacts
            reports
